<div float: center>
    <img src="../common/../common/logo_DH.png" width="30%" height="30%" style="text-align: left;">
    <img src="../common/wipro_logo.png"  width="20%" height="20%" style="text-align: right; margin-left:400px;">
<div/>

---

# WORKSHOP 4 - Trabajo integrador de DataScience

## GRUPO 8

Integrantes:
- Agustín García 
- Florencia Mosconi
- Ezequiel López Mondo 
- Pablo Bauer 

<a id="tabla_contenidos"></a> 
## Tabla de Contenidos

### <a href='#section_repaso'>1. Introducción</a>
- #### <a href='#explicacion_dataset'>1.1 Presentación del caso</a>
- #### <a href='#metodologia'>1.2 La metodología de trabajo</a>

### <a href='#section_import_lib'>2. Importación de librerías para casos de Clasificación</a>


### <a href='#importar_dataset'>3. Importando el DataSet</a> 
- #### <a href='#imputacion'>3.1 Imputación de datos</a>

### <a  href='#preparacion_entrenamiento'>4. Preparación y Entrenamiento del DataSet</a>
- #### <a href='#features'>4.1 Features y dummies</a>
- #### <a href='#split'>4.2 Split del set de entrenamiento</a>
- #### <a href='#metodo_entrenamiento'>4.3 Selección del método de entrenamiento</a>

### <a  href='#evaluacion_modelos'>5. Evaluación de los Modelos Métricas</a>

### <a href='#section_curva_roc'>6. Curva ROC</a>
- #### <a href='#section_umbrales'>6.1 Ajustando los umbrales</a>
- #### <a href='#section_imp_croc'>6.2 Implementación Curva ROC y AUC</a>

### <a href='#conclusiones'>7. Conclusuiones</a>
---

<a id="section_repaso"></a> 
## 1. Introducción
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>

<a id="explicacion_dataset"></a> 
### 1.1 Presentación del caso

<img src="../common/solar_farms.png"  width="100%" height="100%">

:es:

**Objetivo del Poryecto**

El objetivo de este proyecto es optimizar la producción de energía solar de una empresa de líder en el campo. Para ello, se requiere desarrollar un modelo de predicción capaz de predecir los valores de 'Clearsky DHI', 'Clearsky DNI' y 'Clearsky GHI', que son índices de incidencia solar clave.

Utilizando un conjunto de datos recopilados durante 10 años con un intervalo de 30 minutos, se entrenará el modelo de predicción. Este modelo permitirá predecir la capacidad de producción de una granja solar en función de ciertos parámetros meteorológicos relevantes.

El objetivo final es proporcionar a la empresa de generación de energía solar una herramienta precisa y confiable para optimizar la producción. Esto permitirá una planificación más eficiente de las operaciones, una mejor gestión de los recursos disponibles y proporcionar valores de entrega de energía, basados en predicciones meteorológicas a través de los servicios de Meteorología Nacionales.

Con este proyecto, se busca aprovechar al máximo el potencial de la energía solar y contribuir a un enfoque más sostenible y respetuoso con el medio ambiente en la generación de energía.

---

:us:

**Goal of the Project**

*The objective of this project is to optimize the solar energy production of a leading company in the field. For this, it is necessary to develop a prediction model capable of predicting the values of 'Clearsky DHI', 'Clearsky DNI' and 'Clearsky GHI', which are key solar incidence indices.

*Using a data set collected over 10 years with an interval of 30 minutes, the prediction model will be trained. This model will make it possible to predict the production capacity of a solar farm based on certain relevant meteorological parameters.

*The ultimate goal is to provide the solar power generation company with an accurate and reliable tool to optimize production. This will allow for more efficient planning, better management of available resources and will provide energy delivery values, based on weather predictions through the National Meteorology services.

*This project seeks to make the most of the potential of solar energy and contribute to a more sustainable and environmentally friendly approach to power generation.


:es:

#### Contexto

Wipro Limited (NYSE: WIT, BSE: 507685, NSE: WIPRO) es una empresa líder mundial en servicios de tecnología de la información, consultoría y procesos comerciales. Aprovechamos el poder de la computación cognitiva, la hiperautomatización, la robótica, nubes, el análisis y las tecnologías emergentes para ayudar a nuestros clientes a adaptarse al mundo digital y hacerlos exitosos. Una empresa reconocida a nivel mundial por su cartera integral de servicios, fuerte compromiso con la sostenibilidad y capital humano comprometido, tenemos más de 220 000 empleados dedicados, que atienden a clientes en seis continentes. Juntos, descubrimos ideas y conectamos los puntos para construir un futuro mejor y más audaz.

Además de ser un líder mundial en servicios de inteligencia artificial según los últimos informes de analistas como Forrester, IDC y Everest Group, Wipro ha sido calificada como la segunda mejor organización para que los científicos de datos trabajen en India en 2021 por Analytics India Magazine. La compañía también se ha comprometido a alcanzar unas emisiones netas de gases de efecto invernadero cero para 2040.

Aunque un poco tarde, el mundo se está dando cuenta del efecto nocivo de los combustibles fósiles en nuestro medio ambiente. A medida que avanza el reloj del fin del mundo, los seres humanos recurren a las energías renovables para evitar un posible apocalipsis. Afortunadamente, el sol es un manantial de energía limpia. Siguiendo el ejemplo, Wipro, en asociación con MachineHack, ha diseñado un desafío de pronóstico para optimizar la generación de energía solar utilizando modelos ML.

---
:us:

#### Context

*Wipro Limited (NYSE: WIT, BSE: 507685, NSE: WIPRO) is a leading global information technology, consulting and business process services company. We harness the power of cognitive computing, hyper-automation, robotics, cloud, analytics and emerging technologies to help our clients adapt to the digital world and make them successful. A company recognized globally for its comprehensive portfolio of services, strong commitment to sustainability and good corporate citizenship, we have over 220,000 dedicated employees serving clients across six continents. Together, we discover ideas and connect the dots to build a better and a bold new future.*

*Along with being a global leader in artificial intelligence services from the latest reports of analysts like Forrester, IDC and Everest Group, Wipro has been rated as the second-best organization for data scientists to work in India in 2021 by Analytics India Magazine. The company has also been committed to reaching a Net-Zero Greenhouse Gas Emissions by 2040.*

*Though a little late in the day, the world is waking up to the deleterious effect of fossil fuels on our environment. As the doomsday clock ticks away, human beings are turning to renewable energy to avert a possible apocalypse. Fortunately, the sun is a well-spring of clean energy. Taking the cue, Wipro, in association with MachineHack, has designed a forecasting challenge to optimise solar power generation using ML models.*

---

['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'Fill Flag', 'Relative Humidity', 'Solar Zenith Angle', 'Pressure', 'Precipitable Water', 'Wind Direction', 'Wind Speed']

#### Columnas
- **Year** - Año de toma de datos
- **Month** - Mes de toma de datos
- **Day** - Día de toma de datos
- **Hour** - Hora de toma de datos
- **Minute** - Minuto de toma de datos
- **Temperature** - Temperatura local
- **Clearsky_DHI** - Diffuese Horizontal Irradiance
- **Clearsky_DNI** - Direct Normal Irradiance
- **Clearsky_GHI** - Global Horizontal Irradiance
- **Cloud_Type** - Tipo de Nubosidad en el ambiente
    - Cloud Type 0 Clear
    - Cloud Type 1 Probably Clear
    - Cloud Type 2 Fog
    - Cloud Type 3 Water
    - Cloud Type 4 Super-Cooled Water
    - Cloud Type 5 Mixed
    - Cloud Type 6 Opaque Ice
    - Cloud Type 7 Cirrus
    - Cloud Type 8 Overlapping
    - Cloud Type 9 Overshooting
    - Cloud Type 10 Unknown
    - Cloud Type 11 Dust
    - Cloud Type 12 Smoke
    - Cloud Type -15 N/A
- **Dew_Point** - Punto de rocío
- **Fill_Flag** - 
    - Fill Flag 0 N/A
    - Fill Flag 1 Missing Image
    - Fill Flag 2 Low Irradiance
    - Fill Flag 3 Exceeds Clearsky
    - Fill Flag 4 Missing Cloud Properties
    - Fill Flag 5 Rayleigh Violation
    - Fill Flag any N/A
- **Relative_Humidity** - Humedad relativa
- **Solar_Zenith_Angle** - Ángulo de zenit solar
- **Pressure** - Presión atomsférica
- **Precipitable_Water** - Precipitación de lluvia en mm
- **Wind_Direction** - Dirección del viento
- **Wind_Speed** - Velocidad del viento

<a id="metodologia"></a> 
### 1.2 La metodología de trabajo

Hemos estructurado nuestra metodología de trabajo en varias tareas con el fin de cumplir con nuestros objetivos principales. El objetivo primario es desarrollar un sistema predictivo en la notebook y crear una presentación en PowerPoint, tal como se requiere en el curso.

Además de esto, hemos definido una serie de tareas complementarias para cumplir con nuestro objetivo secundario. Este objetivo implica poner en producción una pequeña página web en un servidor local, la cual contará con las funcionalidades mínimas necesarias para el funcionamiento del sistema y permitirá realizar consultas.

A través de esta metodología, aseguramos un enfoque ordenado y organizado para alcanzar tanto el objetivo primario como el secundario. Cada tarea predictiva se realizará de manera paralela, permitiendo una progresión lógica en el desarrollo del proyecto y permitiendo un proceso comparativo de distintos modelos de aprendizaje. De esta manera, podremos cumplir con los requisitos del curso y también lograr la puesta en funcionamiento del sistema en una página web, brindando una solución más completa y accesible para los usuarios.

Esta metodología nos permite maximizar la eficiencia y garantizar la entrega exitosa de los resultados esperados en los plazos establecidos.

<a id="section_import_lib"></a>
## 2. Importación de librerías para casos de Clasificación
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

<a id="importar_dataset"></a>
## 3. Importando el DataSet
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>

In [2]:
ruta_X_train = "../data/train.csv"
ruta_X_test = "../data/test.csv"
ruta_sample_submission = "../data/sample_submission.csv"

# Con este data set crearemos los DF de entrenamiento y testeo
data = pd.read_csv(ruta_X_train, sep=',')

# Este data set quedará como set de prediciones
X_test_ = pd.read_csv(ruta_X_test, sep=',')

# VER QUE HACEMOS CON ESTO, YO LO ELIMINARÍA
sample_submission = pd.read_csv(ruta_sample_submission, sep=',')

print(data.shape)
print(X_test_.shape)

(175296, 18)
(17520, 18)

In [3]:
data_nan = data.apply(lambda x: x.isnull().sum()/x.shape[0], axis=0)
data_nan

Year                  0.0
Month                 0.0
Day                   0.0
Hour                  0.0
Minute                0.0
Clearsky DHI          0.0
Clearsky DNI          0.0
Clearsky GHI          0.0
Cloud Type            0.0
Dew Point             0.0
Temperature           0.0
Pressure              0.0
Relative Humidity     0.0
Solar Zenith Angle    0.0
Precipitable Water    0.0
Wind Direction        0.0
Wind Speed            0.0
Fill Flag             0.0
dtype: float64

Podemos observar que el DataSet no contiene ningún nulo, ya que este fue tomado por una computadore de manera continua de los datos climaticos de la zona.

<a id="imputacion"></a> 
### 3.1 Imputación de datos

En esta imputación encontramos una discrepancia en la organización de las columnas y hacemos un arreglo para que tengan el  mismo orden del DataSet que utilizaremos al final de trabajo para realizar predicciones futuras.

In [4]:
X_test_.columns.values

array(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Cloud Type',
       'Dew Point', 'Temperature', 'Pressure', 'Relative Humidity',
       'Solar Zenith Angle', 'Precipitable Water', 'Wind Direction',
       'Wind Speed', 'Fill Flag', 'Clearsky DHI', 'Clearsky DNI',
       'Clearsky GHI'], dtype=object)

In [5]:
data = data[['Year', 'Month', 'Day', 'Hour', 'Minute', 'Cloud Type',
       'Dew Point', 'Temperature', 'Pressure', 'Relative Humidity',
       'Solar Zenith Angle', 'Precipitable Water', 'Wind Direction',
       'Wind Speed', 'Fill Flag', 'Clearsky DHI', 'Clearsky DNI',
       'Clearsky GHI']]

data.sample(5)

,Year,Month,Day,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,Wind Direction,Wind Speed,Fill Flag,Clearsky DHI,Clearsky DNI,Clearsky GHI
137430,2016,11,3,3,0,8,15.0,21.0,1010,70.27,144.25,2.797,105.4,1.5,0,0,0,0
172048,2018,10,25,8,0,7,8.1,12.4,1008,74.81,138.22,1.300,75.0,2.6,0,0,0,0
12939,2009,9,27,13,30,4,21.0,22.0,1000,98.10,65.19,2.934,314.4,2.8,0,83,700,377
28290,2010,8,13,9,0,3,25.0,25.0,1000,100.00,113.30,6.035,227.0,1.8,0,0,0,0
123293,2016,1,13,14,30,0,1.0,5.0,1010,75.48,70.71,0.508,341.6,2.4,0,59,823,331

<a id="preparacion_entrenamiento"></a>
## 4. Preparación y Entrenamiento del DataSet
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>

En esta sección trabajaremos el DataSet con profundidad para dejarlo listo y en condiciones, con la intención de enfocarnos en las distintas estrategias de entrenameinto, como veremos más adelante.

<a id="features"></a> 
### 4.1 Features y dummies

En el DataSet paraeciera no haber Features de clasificación, pero estás si están. Se encuentran establecidas con valores numéricos identificando las categorías que representan. Las Features de las que estamos hablando son, **Cloud Type** y **Fill Flag**. Dentro de las mismas hay un total de 22 clasificadores. Por este motivo será necesario identificar dummies que puedan estar relacionadas a nuestros vectores Target de los datos meteorológicos.

In [6]:
data.columns.values

array(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Cloud Type',
       'Dew Point', 'Temperature', 'Pressure', 'Relative Humidity',
       'Solar Zenith Angle', 'Precipitable Water', 'Wind Direction',
       'Wind Speed', 'Fill Flag', 'Clearsky DHI', 'Clearsky DNI',
       'Clearsky GHI'], dtype=object)

In [7]:
def cloud_type_cat(x):
    if x == 0:
        return 'Clear'
    elif x == 1:
        return 'Probably_Clear'
    elif x == 2:
        return 'Fog'
    elif x == 3:
        return 'Water'
    elif x == 4:
        return 'Super_Cooled_Water'
    elif x == 5:
        return 'Mixed'
    elif x == 6:
        return 'Opaque_Ice'
    elif x == 7:
        return 'Cirrus'
    elif x == 8:
        return 'Overlapping'
    elif x == 9:
        return 'Overshooting'
    elif x == 10:
        return 'Unknown'
    elif x == 11:
        return 'Dust'
    elif x == 12:
        return 'Smoke'
    elif x == -15:
        return 'N/A'
    else:
        return np.nan
        
data['cloud_type_cat'] = data['Cloud Type'].apply(cloud_type_cat)
data['cloud_type_cat'].value_counts()

Clear                 82788
Cirrus                23163
Water                 16255
Probably_Clear        15698
Overlapping           14276
Super_Cooled_Water    11738
Opaque_Ice             7902
Fog                    3018
Overshooting            457
Unknown                   1
Name: cloud_type_cat, dtype: int64

In [9]:
data

,Year,Month,Day,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,Wind Direction,Wind Speed,Fill Flag,Clearsky DHI,Clearsky DNI,Clearsky GHI,cloud_type_cat
0,2009,1,1,0,0,0,0.0,5.0,1010,75.34,106.15,0.499,346.1,3.1,0,0,0,0,Clear
1,2009,1,1,0,30,0,1.0,5.0,1010,80.81,112.28,0.490,346.1,3.1,0,0,0,0,Clear
2,2009,1,1,1,0,4,0.0,5.0,1010,78.27,118.50,0.482,347.9,3.2,0,0,0,0,Super_Cooled_Water
3,2009,1,1,1,30,4,0.0,4.0,1010,78.27,124.78,0.478,347.9,3.1,0,0,0,0,Super_Cooled_Water
4,2009,1,1,2,0,4,0.0,4.0,1010,76.45,131.12,0.475,350.0,3.0,0,0,0,0,Super_Cooled_Water
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175291,2018,12,31,21,30,4,19.4,20.8,1008,91.77,77.86,3.700,204.0,3.5,100,51,555,168,Super_Cooled_Water
175292,2018,12,31,22,0,4,19.1,20.1,1008,93.88,83.03,3.800,209.0,3.2,100,37,388,84,Super_Cooled_Water
175293,2018,12,31,22,30,7,19.1,19.6,1008,96.83,88.32,3.800,208.0,2.6,57,15,115,18,Cirrus
175294,2018,12,31,23,0,7,18.7,19.2,1009,96.84,94.34,3.700,206.0,2.1,0,0,0,0,Cirrus
175295,2018,12,31,23,30,7,18.7,19.2,1009,96.84,100.22,3.700,206.0,2.1,0,0,0,0,Cirrus

In [15]:
def flag_cat(x):
    if x == 0:
        return 'N/A'
    elif x == 1:
        return 'Missing_Image'
    elif x == 2:
        return 'Low_Irradiance'
    elif x == 3:
        return 'Exceeds_Clearsky'
    elif x == 4:
        return 'Missing_Cloud_Properties'
    elif x == 5:
        return 'Rayleigh_Violation'
    else:
        return 'Other'

data['fill_flag_cat'] = data['Fill Flag'].apply(flag_cat)
data['fill_flag_cat'].value_counts()

N/A                         164285
Missing_Cloud_Properties      6864
Missing_Image                 2046
Other                         1811
Exceeds_Clearsky               290
Name: fill_flag_cat, dtype: int64

In [16]:
data

,Year,Month,Day,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,Wind Direction,Wind Speed,Fill Flag,Clearsky DHI,Clearsky DNI,Clearsky GHI,cloud_type_cat,fill_flag_cat
0,2009,1,1,0,0,0,0.0,5.0,1010,75.34,106.15,0.499,346.1,3.1,0,0,0,0,Clear,N/A
1,2009,1,1,0,30,0,1.0,5.0,1010,80.81,112.28,0.490,346.1,3.1,0,0,0,0,Clear,N/A
2,2009,1,1,1,0,4,0.0,5.0,1010,78.27,118.50,0.482,347.9,3.2,0,0,0,0,Super_Cooled_Water,N/A
3,2009,1,1,1,30,4,0.0,4.0,1010,78.27,124.78,0.478,347.9,3.1,0,0,0,0,Super_Cooled_Water,N/A
4,2009,1,1,2,0,4,0.0,4.0,1010,76.45,131.12,0.475,350.0,3.0,0,0,0,0,Super_Cooled_Water,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175291,2018,12,31,21,30,4,19.4,20.8,1008,91.77,77.86,3.700,204.0,3.5,100,51,555,168,Super_Cooled_Water,Other
175292,2018,12,31,22,0,4,19.1,20.1,1008,93.88,83.03,3.800,209.0,3.2,100,37,388,84,Super_Cooled_Water,Other
175293,2018,12,31,22,30,7,19.1,19.6,1008,96.83,88.32,3.800,208.0,2.6,57,15,115,18,Cirrus,Other
175294,2018,12,31,23,0,7,18.7,19.2,1009,96.84,94.34,3.700,206.0,2.1,0,0,0,0,Cirrus,N/A
175295,2018,12,31,23,30,7,18.7,19.2,1009,96.84,100.22,3.700,206.0,2.1,0,0,0,0,Cirrus,N/A

<a id="split"></a> 
### 4.2 Split del set de entrenamiento
En esta seccion crearemos los datos de entrenamiento y los vectores objetivos multi nivel, para finalemente comenzar con las estrategias de entrenamiento.

In [ ]:
X = data.drop(['Clearsky DHI', 'Clearsky DNI',
       'Clearsky GHI'], axis=1)
y = data[['Clearsky DHI', 'Clearsky DNI',
       'Clearsky GHI']]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12,  test_size=0.3)

<a id="metodo_entrenamiento"></a> 
### 4.3 Selección del método de entrenamiento
Escribir aquí...  **# TO-DO**

<a id="evaluacion_modelos"></a>
## 5. Evaluación de los Modelos
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>

<a id="section_curva_roc"></a> 
## 6. Curva ROC
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>

<a id="section_umbrales"></a> 
### 6.1 Ajustando los umbrales

<a id="section_imp_croc"></a> 
### 6.2 Implementación Curva ROC y AUC

<a id="conclusiones"></a> 
## 7. Conclusiones
---
<a href='#tabla_contenidos'>Volver a la Tabla de Contenidos</a>